package compress

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/cloud-byte-consulting/cachy/internal/tokens"
)

func TestNativeStructuredCompressorMinifiesValidJSON(t *testing.T) {
	t.Parallel()

	original := `{
		"status": "failed",
		"items": [
			{
				"name": "database",
				"error": "timeout"
			}
		]
	}`

	proposal, err := NativeStructuredCompressor{}.Compress(Block{
		ID:          "block_1",
		ContentType: ContentJSON,
		Text:        original,
	})
	if err != nil {
		t.Fatalf("Compress() error = %v", err)
	}

	if len(proposal.Text) >= len(original) {
		t.Fatalf("proposal length = %d, want shorter than %d", len(proposal.Text), len(original))
	}
	if !json.Valid([]byte(proposal.Text)) {
		t.Fatalf("proposal is not valid JSON: %q", proposal.Text)
	}
	if !strings.Contains(proposal.Text, `"error":"timeout"`) {
		t.Fatalf("proposal missing JSON signal: %q", proposal.Text)
	}
}

func TestNativeStructuredCompressorLeavesMalformedJSONForValidationFallback(t *testing.T) {
	t.Parallel()

	original := `{"status":"failed",`
	proposal, err := NativeStructuredCompressor{}.Compress(Block{
		ID:          "block_1",
		ContentType: ContentJSON,
		Text:        original,
	})
	if err != nil {
		t.Fatalf("Compress() error = %v", err)
	}
	if proposal.Text != original {
		t.Fatalf("proposal = %q, want malformed JSON unchanged", proposal.Text)
	}
}

func TestNativeStructuredCompressorReducesDiffContext(t *testing.T) {
	t.Parallel()

	diff := strings.Join([]string{
		"diff --git a/app.go b/app.go",
		"index 1111111..2222222 100644",
		"--- a/app.go",
		"+++ b/app.go",
		"@@ -1,8 +1,8 @@",
		" package main",
		" import \"fmt\"",
		" func main() {",
		"-    fmt.Println(\"old\")",
		"+    fmt.Println(\"new\")",
		" }",
		" // trailing context",
	}, "\n")

	proposal, err := NativeStructuredCompressor{}.Compress(Block{
		ID:          "block_1",
		ContentType: ContentDiff,
		Text:        diff,
	})
	if err != nil {
		t.Fatalf("Compress() error = %v", err)
	}

	if len(proposal.Text) >= len(diff) {
		t.Fatalf("proposal length = %d, want shorter than %d", len(proposal.Text), len(diff))
	}
	for _, want := range []string{"diff --git", "--- a/app.go", "+++ b/app.go", "@@ -1,8 +1,8 @@", `-    fmt.Println("old")`, `+    fmt.Println("new")`} {
		if !strings.Contains(proposal.Text, want) {
			t.Fatalf("proposal missing diff signal %q:\n%s", want, proposal.Text)
		}
	}
	if !strings.Contains(proposal.Text, "diff context lines omitted") {
		t.Fatalf("proposal does not describe omitted context:\n%s", proposal.Text)
	}
}

func TestNativeStructuredCompressorReducesGeneratedCodeNoise(t *testing.T) {
	t.Parallel()

	code := strings.Join([]string{
		"// Code generated by fixture. DO NOT EDIT.",
		"// Code generated by fixture. DO NOT EDIT.",
		"// Code generated by fixture. DO NOT EDIT.",
		"package generated",
		"",
		"",
		"func Value() string {",
		"    return \"kept\"",
		"}",
	}, "\n")

	proposal, err := NativeStructuredCompressor{}.Compress(Block{
		ID:          "block_1",
		ContentType: ContentCode,
		Text:        code,
	})
	if err != nil {
		t.Fatalf("Compress() error = %v", err)
	}

	if len(proposal.Text) >= len(code) {
		t.Fatalf("proposal length = %d, want shorter than %d", len(proposal.Text), len(code))
	}
	if strings.Count(proposal.Text, "Code generated") != 1 {
		t.Fatalf("proposal = %q, want generated comment kept once", proposal.Text)
	}
	if !strings.Contains(proposal.Text, "func Value() string") || !strings.Contains(proposal.Text, `return "kept"`) {
		t.Fatalf("proposal missing code signal:\n%s", proposal.Text)
	}
}

func TestNativeCompressorRoutesStructuredContentThroughValidationPipeline(t *testing.T) {
	t.Parallel()

	original := "{\n  \"status\": \"failed\",\n  \"error\": \"timeout\",\n  \"retryable\": true\n}"
	counters := tokens.NewCounterSet()
	counters.RegisterExact(string(ProviderOpenAI), "gpt-test", tokens.CounterFunc(func(text string) (tokens.Count, error) {
		return tokens.Count{Tokens: len(text), Method: "fixture_chars"}, nil
	}))
	pipeline := NewPipeline(PipelineOptions{
		Counters: counters,
		ProviderModel: tokens.ProviderModel{
			Provider: string(ProviderOpenAI),
			Model:    "gpt-test",
		},
		Compressor: NativeCompressor{},
	})

	result, err := pipeline.Apply([]Block{{
		ID:          "block_1",
		Provider:    ProviderOpenAI,
		ContentType: ContentJSON,
		Text:        original,
		Selected:    true,
		Stability:   StabilityLive,
	}})
	if err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	if !result.Decisions[0].Applied {
		t.Fatalf("decision = %#v, want validation to apply minified JSON", result.Decisions[0])
	}
	if !json.Valid([]byte(result.Blocks[0].Text)) {
		t.Fatalf("compressed block is not valid JSON: %q", result.Blocks[0].Text)
	}
}
